[package]
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
description = "Hitachi HD44780 support for STM32"
name = "hd44780"
version = "0.1.1-pre"

[dependencies.fast_fmt]
optional = true
default-features = false
features = []
version = "0.1.1"

[features]
default = []
fast-format = ["fast_fmt"]

[dependencies]
cortex-m = "0.2.6"
